### ISSUE TITLE
TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by priyankar2017** [jvillagomez/rssi_module#1]
I wish to extract list of wifi access points along with there signal strength. The library is working fine with Python 2.7.15. When I execute the file in Python 3.6.8. the following error is shown on terminal
========================ERROR 
![python2_output](https://user-images.githubusercontent.com/47940169/53298237-f5917300-3850-11e9-8f54-73ca38b00412.png)
![python3_output](https://user-images.githubusercontent.com/47940169/53298238-f5917300-3850-11e9-941b-1996114c6860.png)

=================================
[b'IITRPR', b'GUEST-TEST']
Traceback (most recent call last):
  File "BluetoothDetection.py", line 11, in <module>
    ap_info = rssi_scanner.getAPinfo(networks=ssids, sudo=False)
  File "/home/clab/anaconda3/envs/rssi/lib/python3.6/site-packages/rssi/__init__.py", line 305, in getAPinfo
    all_access_points = self.formatCells(raw_scan_output)
  File "/home/clab/anaconda3/envs/rssi/lib/python3.6/site-packages/rssi/__init__.py", line 203, in formatCells
    raw_cells = raw_cell_string.split('Cell') # Divide raw string into raw cells.
TypeError: a bytes-like object is required, not 'str'
========================CODE=================================
import rssi
interface = 'wlp2s0'  # use iwconfig command on terminal to get interface value
rssi_scanner = rssi.RSSI_Scan(interface)
a = 'IITRPR'
b = a.encode('utf-8')
a = 'GUEST-TEST'
c = a.encode('utf-8')
ssids = [b,c] # Names os ssids
print(ssids)
ap_info = rssi_scanner.getAPinfo(networks=ssids, sudo=False)
print(ap_info)

**Comment by mchaudh4** [comment]
Hello Sir, i tried my level best to run your code, but i am not getting any results. Please help.

**Comment by ApocalyVec** [comment]
I'm also having the same issue. I ran the code on a MAC. Here's the terminal command and the error I'm getting:
$ scanner.getAPinfo(sudo=True)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/Leo/PycharmProjects/ApocalyWarDrive/venv/lib/python3.6/site-packages/rssi/__init__.py", line 305, in getAPinfo
    all_access_points = self.formatCells(raw_scan_output)
  File "/Users/Leo/PycharmProjects/ApocalyWarDrive/venv/lib/python3.6/site-packages/rssi/__init__.py", line 203, in formatCells
    raw_cells = raw_cell_string.split('Cell') # Divide raw string into raw cells.
TypeError: a bytes-like object is required, not 'str'

**Comment by stefanomoro** [comment]
I'm having the same issue. But with Python 2 it works fine

**Comment by stefanomoro** [comment]
To solve this issue in Python3 you just have to add one line of code in the `__init__.py` at line 67 in the 
`getRawNetworkScan` function

`raw_output = raw_output.decode('utf-8')`

It was a problem with the encoding of the string output by the raw scan

**Comment by navado** [comment]
@stefanomoro any chance for a pull request and re-publish at pipi?

**Comment by stefanomoro** [comment]
@navado Good idea. I will try to do it

**Comment by shanepisko** [comment]
can confirm this worked for me as well

**Comment by jvillagomez** [comment]
Hello everyone. I apologize for the previous lack of support. I'm now maintaining the project and will be adding new features (some in sibling repos) over the next few days.

I have added a fix for usage in python3 in this repo, and will reflect the changes across the pip package as well.

**Comment by skeever** [comment]
> To solve this issue in Python3 you just have to add one line of code in the `__init__.py` at line 67 in the
> `getRawNetworkScan` function
> 
> `raw_output = raw_output.decode('utf-8')`
> 
> It was a problem with the encoding of the string output by the raw scan

This did the trick for me! I wonder if that works in other situations...

**Comment by Hassen1993** [comment]
Waiting for connection from Robot!
UDP-Connection from 192.168.0.41:1051!
Traceback (most recent call last):
  File "pprobot_musterloesung.py", line 35, in <module>
    rob = PPRobot(IdealPlayer)
  File "/home/student/Desktop/mrtpprobot/pprobot_python3_2/PPRobot/__init__.py", line 27, in __init__
    self._robot.wait_for_connection()
  File "/home/student/Desktop/mrtpprobot/pprobot_python3_2/PPRobot/RobotControl/communication.py", line 399, in wait_for_connection
    self._dsocket.sendto(s,adr)
TypeError: a bytes-like object is required, not 'str'


please i need help
