### ISSUE TITLE
Added MAC addr to cell

### ISSUE THREAD

**Issue by JLBicho** [jvillagomez/rssi_module#5]
Hi! 
I have added a small piece of code to retrieve the MAC address, in case you have several routers with the same SSID and need to differentiate using MAC address.
The code is as follows:
`def getMACaddr(raw_cell):`
&nbsp;&nbsp;&nbsp;&nbsp;`addr = raw_cell.split('Address: ')[1]`
&nbsp;&nbsp;&nbsp;&nbsp;`addr = addr.split(' ')[0]`
&nbsp;&nbsp;&nbsp;&nbsp;`addr = addr[0:len(addr)-1]`
&nbsp;&nbsp;&nbsp;&nbsp;`return addr`
And the small modification in the parseCell function:
`def parseCell(raw_cell):`
&nbsp;&nbsp;&nbsp;&nbsp;`cell = {`
&nbsp;&nbsp;&nbsp;&nbsp;`'ssid': getSSID(raw_cell),`
&nbsp;&nbsp;&nbsp;&nbsp;`'quality': getQuality(raw_cell),`
&nbsp;&nbsp;&nbsp;&nbsp;`'signal': getSignalLevel(raw_cell),`
&nbsp;&nbsp;&nbsp;&nbsp;`'MAC': getMACaddr(raw_cell)`
&nbsp;&nbsp;&nbsp;&nbsp;`}`
&nbsp;&nbsp;`return cell`
I hope it is helpful. Thank you for the library, it is very useful!

Saludos desde Madrid, España

**Comment by jvillagomez** [comment]
Hi @JLBicho , Thank you for the props. Would you like to open a PR to add your functionality? 
I will be adding new features to this module over the next few days. This seems like something cool to add, but I do not want to take credit for your work.

Maybe we can rename to **getMacAddress** and **mac** for the object key...


Please checkout the README to see features coming. Let me know if you'd like to see another feature added!

**Comment by JLBicho** [comment]
Hi @jvillagomez,
Thank you for your answer. I will gladly make a PR, I will try to do it as soon as possible. 

Thank you for your work!
